# Generated by Django 5.1 on 2024-08-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('subject', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.speaker')),
            ],
        ),
    ]
